import { useEffect,useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import College from '../src/common/College'
import { fetchColleges } from '../src/lib/fetch'
import Navigation from '../src/common/Navigation'
import {Colleges} from '@prisma/client'
import SimpleBar from 'simplebar-react'

export async function getServerSideProps() {
  const colleges = await fetchColleges();
  return {
    props: {
      colleges: colleges || []
    }
  }
  
}

const Home: NextPage = ({colleges}:any) => {
  const [reactColleges, setColleges] = useState<JSX.Element[]>([])
  
  const filterColleges = (e:any) => {
  let colls = colleges.filter((college:any) => {
    return college.name.toLowerCase().includes(e.target.value.toLowerCase())
  })
  setColleges(colls.map(mapColleges))
  }

  const mapColleges = (college:Colleges) => {
   return <College 
      key={college.name}
      name={college.name}
      description={college.description}
      logo={college.logo}
      id={college.id}
    />
  }
  
  useEffect(() => {
    setColleges(colleges.map(mapColleges))
  },[colleges])
  return (
    <div className={styles.container}>
      <Head>
        <title>Find Colleges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <div className={`${styles.title} ${styles.findCollegeTitle}`}>
          <input onChange={filterColleges} type="text" placeholder="Search for a college" />
        </div>
        {reactColleges.length > 0 && <SimpleBar className={styles.scroll} forceVisible="y" autoHide={false} style={{maxHeight: 800}}>
        {reactColleges}
        </SimpleBar>}
      </main>
     <br />

    </div>
  )
}

export default Home
