import { useEffect,useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import College from '../src/common/College'
import { fetchCollegesFromQuery } from '../src/lib/fetch'
import Navigation from '../src/common/Navigation'
import {Colleges} from '@prisma/client'
import {useSession} from 'next-auth/react'
import SimpleBar from 'simplebar-react'
import CollegeModal from '../src/common/modal/CollegeModal';
import AuthModal from '../src/common/modal/AuthModal';
import Router from 'next/router'

export async function getServerSideProps({query}:any) {
  const colleges = await fetchCollegesFromQuery(query.query);
  
  return {
    props: {
      colleges: colleges,
	  query: query.query
    }
  }
  
}

const Home: NextPage = ({colleges, query}:any) => {
  const [reactColleges, setColleges] = useState<JSX.Element[]>([])
  const {status} = useSession();
  const [isCollegeOpen, setIsCollegeOpen] = useState(false);
  const [isOpen, setIsOpen] = useState(false);


  const mapColleges = (college:Colleges) => {
   return <College 
      key={college.name}
      name={college.name}
      description={college.description}
      logo={college.logo}
      id={college.id}
    />
  }

  const newCollege =() => {
    if (status === 'authenticated'){
      Router.push('/create-community');
    }
    else {
      setIsOpen(true);
    }
  }
  
  useEffect(() => {
    setColleges(colleges.map(mapColleges))
  },[colleges])

  return (
    <div className={styles.container}>
      <Head>
        <title>Search Communities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <h2 className={styles.searchTitle}>Showing search results for <span>{query}</span></h2>
        <p className={styles.dont}>Don&apos;t see a community that fits your needs? <span className={styles.createSearch} onClick={newCollege}>Create a new community.</span></p>
        {reactColleges.length > 0 && <SimpleBar className={styles.scrollFind} forceVisible="y" autoHide={false}>
        {reactColleges}
        </SimpleBar>}
        {reactColleges.length === 0 && <h3 className={styles.noResults}>No results found.</h3>}
      </main>
      <AuthModal callBackUrl={'/create-community'} type={'Login'} setOpen={setIsOpen} isOpen={isOpen} />
      <CollegeModal isOpen={isCollegeOpen} setOpen={setIsCollegeOpen} type={'create'}/>
     <br />
    </div>
  )
}

export default Home
