name: Build and Push NextJS Image to AWS ECR

on:
  push:
    branches:
            [main]

jobs:

    
  build-and-push-and-deploy:
        name: Build and Push NextJS Image to AWS ECR and Deploy Task
        runs-on: ubuntu-latest
        steps:
         
         - name: Checkout
           uses: actions/checkout@v2
         - name: Make envfile
           env:
            PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
           run: |
            touch ${{ github.workspace}}/prisma/.env
            echo $PROD_ENV_FILE > ${{github.workspace}}/.env
            export DATABASE_URL=$DATABASE_URL

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              aws-region: ca-central-1
         - name: Login to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v1

        
         - name: Build Tag, and Push the Image to Amazon ECR
           id: build-image
           env:
             ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
             ECR_REPOSITORY: akose-communities
             IMAGE_TAG: ${{ github.sha }}
             DATABASE_URL: ${{secrets.DATABASE_URL}}

           run: |
            docker build --build-arg DATABASE_URL=$DATABASE_URL -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
         - name: Download task definition
           run: |
             aws ecs describe-task-definition --task-definition AkoseCommunityTask --query taskDefinition > task-definition.json

         - name: Fill in the new image ID in the Amazon ECS task definition
           id: task-def
           uses: aws-actions/amazon-ecs-render-task-definition@v1
           with:
              task-definition: task-definition.json
              container-name: AkoseCommunitiesContainer
              image: ${{ steps.build-image.outputs.image }}

         - name: Deploy Amazon ECS task definition
           uses: aws-actions/amazon-ecs-deploy-task-definition@v1
           with:
             task-definition: ${{ steps.task-def.outputs.task-definition }}
             cluster: AkoseCommunitiesCluster
             wait-for-service-stability: true
            
         - name: 'Automated Version Bump'
           id: version-bump
           uses: 'phips28/gh-action-bump-version@master'
           with:
            tag-prefix: 'v'
           env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}