name: Build and Push NextJS Image to AWS ECR

on:
  push:
    branches:
            [main]

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
       envkey_S3_AWS_ACCESS_KEY_ID: ${{secrets.S3_AWS_ACCESS_KEY_ID}}
       envkey_S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
       envkey_S3_AWS_SECRET_ACCESS_KEY: ${{secrets.S3_AWS_SECRET_ACCESS_KEY}}
       envkey_S3_KEY_PREFIX: ${{secrets.S3_KEY_PREFIX}}
       envkey_FACEBOOK_ID: ${{secrets.FACEBOOK_ID}}
       envkey_FACEBOOK_SECRET: ${{secrets.FACEBOOK_SECRET}}
       envkey_GOOGLE_ID: ${{secrets.GOOGLE_ID}}
       envkey_GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
       envkey_LINKEDIN_ID: ${{secrets.LINKEDIN_ID}}
       envkey_LINKEDIN_SECRET: ${{secrets.LINKEDIN_SECRET}}
       envkey_EMAIL_USER: ${{secrets.EMAIL_USER}}
       envkey_EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
       envkey_EMAIL_SERVICE: ${{secrets.EMAIL_SERVICE}}
       envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
       directory: ./
       file_name: .env
       fail_on_empty: false
      
  build-and-push:
        name: Build and Push NextJS Image to AWS ECR
        runs-on: ubuntu-latest

        services:
          postgres:
            image: postgres:latest
            env:
              POSTGRES_DB: postgres        
              POSTGRES_PASSWORD: postgres
              POSTGRES_USER: postgres
            ports:
              - 5432:5432
        # Set health checks to wait until postgres has started
            options: >-
             --health-cmd pg_isready
             --health-interval 10s
             --health-timeout 5s
             --health-retries 5
        steps: 
         - name: Checkout
           uses: actions/checkout@v2

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              aws-region: ca-central-1
         - name: Login to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v1

         - name: Automatic Tagging of Releases
           id: increment-git-tag
           run: |
              bash ./scripts/git_update.sh --bug 
         - name: Build Tag, and Push the Image to Amazon ECR
           id: build-image
           env:
             ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
             ECR_REPOSITORY: akose-communities
             IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
           run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
