name: Build and Push NextJS Image to AWS ECR

on:
  push:
    branches:
            [main]

jobs:

    
  build-and-push:
        name: Build and Push NextJS Image to AWS ECR
        runs-on: ubuntu-latest
        steps:
         - name: Make envfile
           env:
            PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
           run: |
            touch .env
            echo $PROD_ENV_FILE > .env
            cat .env

         - name: Checkout
           uses: actions/checkout@v2

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              aws-region: ca-central-1
         - name: Login to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v1

         - name: 'Automated Version Bump'
           id: version-bump
           uses: 'phips28/gh-action-bump-version@master'
           with:
            tag-prefix: 'v'
           env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
         - name: Build Tag, and Push the Image to Amazon ECR
           id: build-image
           env:
             ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
             ECR_REPOSITORY: akose-communities
             IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
             DATABASE_URL: ${{ secrets.DATABASE_URL }}
           run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:v.1.0 .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:v0.1.0
